# https://gohugo.io/overview/configuration/

baseurl: 'https://parsiya.io'
disablePathToLower: false
languageCode: en-us
title: Parsia-Clone
theme: Hugo-Octopress

# frontmatter will be generated in yaml format
metadataformat: yaml

# ignore code directory
ignorefiles:
  - ^code\.*
  - \.git\.*
  - README.*

# disable generation of RSS and section pages
disableKinds:
  - section
  - RSS

permalinks:
  post: '/:title/' # only have title in URL

menu:
  main:
    - Name: My Main Website
      URL: 'https://parsiya.net'
      weight: 0
    - Name: Parsia-Clone on Github
      URL: 'https://github.com/parsiya/Parsia-Clone'
      weight: 5
    - Name: How did I make this?
      URL: 'https://parsiya.net/categories/clone/'
      weight: 10

params:

  navigationNewWindow: true
  sidebarHeader: Parsia Clone
  sidebarText: |-
    This is my knowledge base. I call it my clone. I document things here.

      My main website is [parsiya.net](https://parsiya.net) but feel free to look around. You can contact me using one of these ways:


  sidebarMenuEnabled: false
  sidebarMenuHeader: Collections

  notfoundHeader: There's nothing here
  notfoundText: You can never go back.

  # author's name (this will appear in metadata and under posts)
  author: Parsia-Clone

  # appears in the site header under website title
  subtitle: "'Documentation is a love letter that you write to your future self.' - Damian Conway"

  # used in the search engine
  searchEngineURL: 'https://www.google.com/search'

  # bitbucket: 'https://bitbucket.org/parsiya/'
  twitter: 'https://twitter.com/cryptogangsta/'
  # keybase: 'https://keybase.io/parsiya/'
  github: 'https://github.com/parsiya/'
  linkedin: 'https://www.linkedin.com/in/parsiya'
  mastodon: 'https://infosec.exchange/@parsiya'

  # does this even work in action?
  defaultKeywords:
    - Parsia Hakimian
    - Parsiya
    - infosec
    - information security

  tableOfContents: false

  # generate taxonomy list and stuff
  generateTaxonomyList: true

  # Clone repo URL for linking back
  repoURL: 'https://github.com/parsiya/Parsia-Clone/tree/main'

  # Custom CSS
  customCSS:
    - /clone.css

  # Twitter card config
  # Enable with this.
  twitterCardEnabled: true
  # Don't include the @.
  # twitterCardSite = 
  twitterCardDomain: parsiya.io
  # Don't include the @.
  twitterCardAuthor: CryptoGangsta

# markup for Hugo v.60+
markup:
  # Note to future me: The reason is because new links in Goldmark are not
  # opened in a new tab by default. We can use the render hook to make it happen
  # for just markdown links but not image links or linkify links (i.e., URLs in
  # the markdown documents as-is). So before you come and waste a lot of time to
  # switch to Goldmark, don't. Of course, unless this problem has been solved in
  # Goldmark.
  # defaultMarkdownHandler: blackfriday # use Blackfriday
  # blackFriday:
  #   fractions: false
  #   hrefTargetBlank: true
  #   latexDashes: false
  #   nofollowLinks: true
  #   smartDashes: false
  #   smartypants: false

  # Goodbye blackfriday, you have been deprecated.
  # The render hook is not fired for linkify links in Goldmark so we have to
  # replace all of them.
  goldmark:
    extensions:
      typographer: false
    renderer:
      hardWraps: false
      unsafe: true
  
  # Change the defaults for the toc because I want to render every heading in
  # the document.
  tableOfContents:
    endLevel: 7
    startLevel: 1
    # Note to future me: Consider changing the start level to 2 but then you
    # have to go and change it for every blog post that started with a level 1
    # heading.
  highlight:
    # use solarized-dark to highlight code.
    style: "solarized-dark"